<a href="https://colab.research.google.com/github/Unju6g/DATA-ANALYSIS/blob/main/CAR_DATASET_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd
import matplotlib.pylab as plt
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [2]:
df = pd.read_excel("Car Sales.xlsx")

In [3]:
df.head(5)

,Car_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
0,C_CND_000001,2022-01-02,Geraldine,Male,13500,Buddy Storbeck's Diesel Service Inc,Ford,Expedition,DoubleÂ Overhead Camshaft,Auto,Black,26000,06457-3834,SUV,8264678,Middletown
1,C_CND_000002,2022-01-02,Gia,Male,1480000,C & M Motors Inc,Dodge,Durango,DoubleÂ Overhead Camshaft,Auto,Black,19000,60504-7114,SUV,6848189,Aurora
2,C_CND_000003,2022-01-02,Gianna,Male,1035000,Capitol KIA,Cadillac,Eldorado,Overhead Camshaft,Manual,Red,31500,38701-8047,Passenger,7298798,Greenville
3,C_CND_000004,2022-01-02,Giselle,Male,13500,Chrysler of Tri-Cities,Toyota,Celica,Overhead Camshaft,Manual,Pale White,14000,99301-3882,SUV,6257557,Pasco
4,C_CND_000005,2022-01-02,Grace,Male,1465000,Chrysler Plymouth,Acura,TL,DoubleÂ Overhead Camshaft,Auto,Red,24500,53546-9427,Hatchback,7081483,Janesville

In [4]:
df.tail(5)

,Car_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
23901,C_CND_023902,2023-12-31,Martin,Male,13500,C & M Motors Inc,Plymouth,Voyager,Overhead Camshaft,Manual,Red,12000,60504-7114,Passenger,8583598,Pasco
23902,C_CND_023903,2023-12-31,Jimmy,Female,900000,Ryder Truck Rental and Leasing,Chevrolet,Prizm,DoubleÂ Overhead Camshaft,Auto,Black,16000,06457-3834,Hardtop,7914229,Middletown
23903,C_CND_023904,2023-12-31,Emma,Male,705000,Chrysler of Tri-Cities,BMW,328i,Overhead Camshaft,Manual,Red,21000,99301-3882,Sedan,7659127,Scottsdale
23904,C_CND_023905,2023-12-31,Victoire,Male,13500,Chrysler Plymouth,Chevrolet,Metro,DoubleÂ Overhead Camshaft,Auto,Black,31000,53546-9427,Passenger,6030764,Austin
23905,C_CND_023906,2023-12-31,Donovan,Male,1225000,Pars Auto Sales,Lexus,ES300,DoubleÂ Overhead Camshaft,Auto,Pale White,27500,38701-8047,Hardtop,7020564,Middletown

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23906 entries, 0 to 23905
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_id         23906 non-null  object
 1   Date           23906 non-null  datetime64[ns]
 2   Customer Name  23905 non-null  object
 3   Gender         23906 non-null  object
 4   Annual Income  23906 non-null  int64
 5   Dealer_Name    23906 non-null  object
 6   Company        23906 non-null  object
 7   Model          23906 non-null  object
 8   Engine         23906 non-null  object
 9   Transmission   23906 non-null  object
 10  Color          23906 non-null  object
 11  Price ($)      23906 non-null  int64
 12  Dealer_No      23906 non-null  object
 13  Body Style     23906 non-null  object
 14  Phone          23906 non-null  int64
 15  Dealer_Region  23906 non-null  object
dtypes: datetime64[ns](1), int64(3), object(12)
memory usage: 2.9+ MB

In [6]:
df.describe()

,Date,Annual Income,Price ($),Phone
count,23906,2.390600e+04,23906.000000,2.390600e+04
mean,2023-03-01 14:28:10.822387456,8.308403e+05,28090.247846,7.497741e+06
min,2022-01-02 00:00:00,1.008000e+04,1200.000000,6.000101e+06
25%,2022-09-20 00:00:00,3.860000e+05,18001.000000,6.746495e+06
50%,2023-03-13 00:00:00,7.350000e+05,23000.000000,7.496198e+06
75%,2023-09-08 00:00:00,1.175750e+06,34000.000000,8.248146e+06
max,2023-12-31 00:00:00,1.120000e+07,85800.000000,8.999579e+06
std,NaN,7.200064e+05,14788.687608,8.674920e+05

In [7]:
df.isnull()

,Car_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23901,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23902,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23903,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23904,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23905,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df.isnull().sum()

Car_id           0
Date             0
Customer Name    1
Gender           0
Annual Income    0
Dealer_Name      0
Company          0
Model            0
Engine           0
Transmission     0
Color            0
Price ($)        0
Dealer_No        0
Body Style       0
Phone            0
Dealer_Region    0
dtype: int64

In [9]:
df.notnull()

,Car_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23901,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
23902,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
23903,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
23904,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
23905,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [15]:
total_sales = df["Price ($)"].sum()
avg_price = df["Price ($)"].mean()
cars_sold = df.shape[0]

print("Total Sales:", total_sales)
print("Average Price:", avg_price)
print("Cars Sold:", cars_sold)

Total Sales: 671525465
Average Price: 28090.247845729107
Cars Sold: 23906

In [19]:
df.columns = df.columns.str.strip()


df["Date"] = pd.to_datetime(df["Date"])
df["Week"] = df["Date"].dt.isocalendar().week


df["Price ($)"] = pd.to_numeric(df["Price ($)"], errors='coerce')


weekly_sales = df.groupby("Week")["Price ($)"].sum().reset_index()


fig1 = px.line(weekly_sales, x="Week", y="Price ($)",
               title="YTD Sales Weekly Trend")
fig1.show()

In [20]:
body_sales = df.groupby("Body Style")["Price ($)"].sum().reset_index()

fig2 = px.pie(body_sales,
              names="Body Style",
              values="Price ($)",
              hole=0.5,
              title="Sales by Body Style")
fig2.show()

In [21]:
color_sales = df.groupby("Color")["Price ($)"].sum().reset_index()

fig3 = px.pie(color_sales,
              names="Color",
              values="Price ($)",
              hole=0.5,
              title="Sales by Color")
fig3.show()

In [29]:
company_sales = df.groupby("Company").agg({
    "Price ($)": "sum",
    "Model": "count"
}).reset_index()

company_sales.columns = ["Company", "Total Sales", "Cars Sold"]

fig5 = px.bar(company_sales,
              x="Company",
              y="Total Sales",
              title="Company Wise Sales")
fig5.show()